### ISSUE TITLE
Web client 🌍

### ISSUE THREAD

**Issue by martinbonnin** [joreilly/Confetti#1220]
Now that we have deeplinks (see https://github.com/joreilly/Confetti/pull/1214), it would be awesome to serve a web client as well so that clicking a deeplink still displays data if the app is not installed. 

Plus maybe a good showcase for Compose web and Web Assembly? 

If you have any idea how to build this, please leave a reply below or join us in the [#confetti channel](https://app.slack.com/client/T09229ZC6/C051P2HUVKP) of the KotlinLang slack (get your invite [here](https://slack.kotl.in/))

**Comment by joreilly** [comment]
Just to note here that I've been looking at building Wasm based Compose for Web client (in branch right now until all dependencies are available0

**Comment by joreilly** [comment]
Initial version of this has now been merged
