### ISSUE TITLE
AndroidMakers breaks sessions have "service" type causing them to be displayed in white even in dark mode

### ISSUE THREAD

**Issue by mdupierreux** [joreilly/Confetti#1313]
When displaying Android Makers 2024 sessions, breaks are displayed in white even on dark mode. That's because they have the type "service" and not "break".

  <img src="https://github.com/joreilly/Confetti/assets/526001/5de4258e-21d7-4072-b004-8b163442b6e2">  <img src="https://github.com/joreilly/Confetti/assets/526001/82614b33-c907-4523-83ca-cf761df0aeab"  width="45%">

Also, I guess this code is going to be updated to match the theme.

```
    if (session.isService()) {
        modifier = modifier.background(Color.White)
    }
```

**Comment by joreilly** [comment]
ah, thanks....that does look pretty ugly all right :)

**Comment by mdupierreux** [comment]
If service sessions are white (on light mode) what would be the correct color in dark mode ?

**Comment by joreilly** [comment]
I"m not sure tbh what best colour would be to use there (am definitely not a designer :) ) ....maybe one of standard ones with some change in alpha or perhaps tonalElevation as we do with `ConfettiHeaderAndroid` for example

**Comment by mdupierreux** [comment]
Ok, so for breaks and services we shouldn't have the bookmark option ? From what I see, the bookmark option is visible because the breaks for Android Makers have the service type. If the type was correct, the option wouldn't be visible.

```
if (!session.isBreak()) {
            Bookmark(
                isBookmarked = isBookmarked,
                onBookmarkChange = { shouldAdd ->
                    if (!isLoggedIn) {
                        showDialog = true
                        return@Bookmark
                    }
                    if (shouldAdd) {
                        addBookmark(session.id)
                    } else {
                        removeBookmark(session.id)
                    }
                }
            )
        }
```

**Comment by BoD** [comment]
Sorry, I'm also definitely not a designer 😅 -  but on the proposed screenshots [above](https://github.com/joreilly/Confetti/issues/1313#issuecomment-2082163309), it looks like the breaks/service session are actually highlighted and have a importance higher than other session whereas, arguably, it's the opposite 😅 

They should probably have the same color as the background instead.

**Comment by mdupierreux** [comment]
Ok 😄, I'm going to try to find a dimmer color (background on dark theme gives me a full black list 😅 )

**Comment by joreilly** [comment]
I'm not super familiar with options here but wondering what `tonalElevation` might add

**Comment by mdupierreux** [comment]
I will look into it 👍

**Comment by mdupierreux** [comment]
Here's with a tonalElevation of 8dp for sessions and 0dp for services : 

<img src="https://github.com/joreilly/Confetti/assets/526001/f9923ff2-0cba-408d-86e2-ed26ecf723dc" width="45%" />
<img src="https://github.com/joreilly/Confetti/assets/526001/a65a077d-c299-4562-83b4-02eaa5fee62a" width="45%" />

**Comment by joreilly** [comment]
That definitely looks better.  @BoD what you think?

**Comment by joreilly** [comment]
That's merged now
