### ISSUE TITLE
Pre-select current date if applicable

### ISSUE THREAD

**Issue by janseeger** [joreilly/Confetti#1382]
On multi-day conferences the app opens on the first day, not the current day.

Example: DroidCon Berlin
Wed through Fri, app always opens on Wednesday Schedule (even on Thursday and Friday)

This should obviously only be done if the date matches. Selecting the first day is fine otherwise.

**Comment by janseeger** [comment]
[selectedDateIndex is always initialised with 0](https://github.com/joreilly/Confetti/blob/main/iosApp/iosApp/Sessions/SessionListView.swift#L28)

**Comment by joreilly** [comment]
ah, this is in iOS client?  There is logic in Android client to open up on current day (and also scroll to show upcoming talks....but don't think that's implemented on iOS yet.
