### ISSUE TITLE
Move HTML stripping to the backend

### ISSUE THREAD

**Issue by yschimke** [joreilly/Confetti#199]
From https://github.com/joreilly/Confetti/pull/198#discussion_r1070447181

> Indeed, this is only for Fosdem data that is HTML. I can move that logic to the backend

**Comment by martinbonnin** [comment]
Closed in #200. I took over your stripping logic. Let me know if you find other tags to strip (or is there an "official" way to strip HTML?)

**Comment by yschimke** [comment]
https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454

**Comment by yschimke** [comment]
Jokes aside, I think the correct answer if we know content is HTML is JSoup?, and some representation of the strings that closely maps to how we will display them. Maybe annotations for links etc, styles?

**Comment by martinbonnin** [comment]
> Maybe annotations for links etc, styles?

I guess we could support markdown on phones for the description? And a different field for smaller form factors like watches? At the end of the day, I don't think people will read a full description on a smaller device? Or will they?

**Comment by yschimke** [comment]
Agreed.  But that would probably lead me to having a summary section, and in the loading code on the backend populate simple fields.  I think the UI code should be really simple and not making too many product decisions when rendering.

**Comment by martinbonnin** [comment]
Not sure I'm following. What I'm suggesting is having two fields like this in the backend:

```graphql
type Session {
  """
  Full description for use on devices with a lot of real estates like phones/tables
  """
  description(format: TextFormat): String 
  """
  The short description when real estate is scarce (watches). The returned string doesn't contain any formatting nor styling
  """
  shortDescription: String 
}

enum TextFormat {
  """ 
  A markdown string as specified by https://daringfireball.net/projects/markdown/syntax
  """ 
  MARKDOWN
  """
  Plain text with styling and formatting removed. 
  """
  PLAIN
}
```

That means different UI requests and different VM but if we want to keep the load small and the UI uncluttered on the watch I don't think there are a lot of other solutions?

**Comment by martinbonnin** [comment]
👍  reopening this issue because I'm too lazy to create a new one 😁

**Comment by yschimke** [comment]
I actually think Wear will be fine with loading slightly more data, and then choosing not to show it. I'd favour simpler shared code over optimising to avoid fetching slightly more data.

**Comment by martinbonnin** [comment]
So load both `description` and `shorDescription` in the network query?

**Comment by yschimke** [comment]
Yeah, I think so.

**Comment by martinbonnin** [comment]
`shortDescription` is available with https://github.com/joreilly/Confetti/pull/209

It's not perfect but it's there. I'll close this issue and open new ones as we go/improve.
