### ISSUE TITLE
Bookmark should be available for guests

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#302]
The current implementation only supports bookmarking talks if a user is signed in, and there is no way to know that until you actually sign in.

It would be nice if the bookmarking feature could be available for guest users too.

That may create conflicts (offline and online bookmarks), for those I suggest to keep it simple and give preference to the online ones.

**Comment by martinbonnin** [comment]
See also https://github.com/joreilly/Confetti/issues/378

**Comment by martinbonnin** [comment]
Prompt in https://github.com/joreilly/Confetti/pull/381, Let me know what you think!
