### ISSUE TITLE
Filter talks per speaker

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#304]
The speaker tab would be more useful if by clicking on a speaker, besides the description: it would list all of their talks.

That would let me to find my favourite speakers, and see what they will be talking about. Would be nice if one could also check the talk details from there and/or bookmark the talk.

**Comment by joreilly** [comment]
For the specific case of showing session details for particular speaker (in speaker details page for example)... @martinbonnin do we have way right now to specifically query that as part of speaker info returned from backend?

**Comment by martinbonnin** [comment]
@joreilly We don't have that yet. It's tracked [there](https://github.com/joreilly/Confetti/issues/407). Having it in the schema will allow to use the normalized cache to lookup that info without having to write custom logic.

**Comment by marcellogalhardo** [comment]
Checking a speaker details, shows all talks he is giving in the event. Done.
