### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#305]
It would be nice to search talks (title and description) and/or speakers (name and description).

**Comment by marcellogalhardo** [comment]
I'm working on the Search feature for Android, and there are a few UI considerations to be done.

1. I have moved the avatar to the left side, to keep the search button on the top-right (as most apps).
2. The first version will use a default text field but we may want a nicer one as an improvement - there is no Search component on compose yet, so we will need to build our own.

Can you confirm these two points are OK? cc: @joreilly @martinbonnin 

| Search Collapsed | Search Expanded | Filter |
|---|---|---|
| ![Screenshot_1679619083](https://user-images.githubusercontent.com/4348197/227397114-98711f8d-c663-410d-bce9-a21efbcc284e.png) | ![Screenshot_1679619086](https://user-images.githubusercontent.com/4348197/227397132-f902e803-af73-40d4-b56a-1f23b8ae749e.png) | ![Screenshot_1679619095](https://user-images.githubusercontent.com/4348197/227397159-95d68dd1-f674-41be-94f0-0bf45ee939c2.png) |

**Comment by martinbonnin** [comment]
Looks very good to me! Thinking a bit about filters, would we put them in a right drawer? 

My current idea of filters is this (from the Android Makers app):
<img src="https://user-images.githubusercontent.com/3974977/227477031-0861004d-00f6-44b2-83bf-0a4d8673a540.png" width=250/>

**Comment by marcellogalhardo** [comment]
@martinbonnin sounds good. We can also use a bottom sheet instead of a right drawer.

I don't think having two icons side by side will cluster the UI but if it does, we can explore a few alternatives:
- Move search to its own tab, which is a dedicated screen that consolidates both sessions and speakers;
- Place search as the first item in the list and/or on the top bar fixed (I think iOS does something like that?);

I guess we can talk about that once we have both features together. 😄

**Comment by marcellogalhardo** [comment]
@martinbonnin @joreilly an alternative layout, which is more friendly to filter can be:

![Screenshot_1679747565](https://user-images.githubusercontent.com/4348197/227717529-a066bd01-285b-4cea-b401-d67f67d4f984.png)

**Comment by martinbonnin** [comment]
Should it be its own destination in the bottom bar like in the ~Twitter~ Mastodon app for an example? That would allow to return results in all days (which I don't think is the case right now?)

* search => all conference data => separate bottom bar item
* filters => only for the current view => bottom sheet or right drawer

?

**Comment by marcellogalhardo** [comment]
@martinbonnin that would be nice but ideally should aggregate all information (both sessions and speakers), not sure how hard would it be to do it with GraphQL.

I have submitted a CL with general improvements + a new UX, but I can revert the UX if needed (not super convinced).

See #428

**Comment by marcellogalhardo** [comment]
I have reverted the new Search UX, we can discuss it separately and if needed I can submit it (I have created a new branch with it).

Here is an example: 

![Screenshot_1679748903](https://user-images.githubusercontent.com/4348197/227718469-5d96a61b-012d-44ae-831f-f3cd42449dcf.png)

**Comment by martinbonnin** [comment]
> @martinbonnin that would be nice but ideally should aggregate all information (both sessions and speakers), not sure how hard would it be to do it with GraphQL.

We download all the conference data at first launch and then use WorkManager to refresh it in the background so it should be all there (and it's not that big. Fosdem is the biggest and it's way under 1MB IIRC).

So I don't think having instant search with suggestions/autocomplete over the network is a great use case for GraphQL (although I'd be curious to explore). But I think we can get something fairly decent by searching the local data.
