### ISSUE TITLE
Show speaker details in Wear app

### ISSUE THREAD

**Issue by joreilly** [joreilly/Confetti#336]
@yschimke I was going to take a look at this......but just to check first in case it was something you had already been working on?

Would show info along lines of following.

![Screenshot_20230317_084148](https://user-images.githubusercontent.com/6302/225855406-f2d4b355-ebde-492b-b67a-91421405950b.png)

**Comment by yschimke** [comment]
Go for it.  How about I create a task with whatever I'm working on.  Outside of that please, contribute tons of stuff to the Wear app. :)
