### ISSUE TITLE
Move state outside of AccountIcon

### ISSUE THREAD

**Issue by martinbonnin** [joreilly/Confetti#375]
Currently, `AccountIcon` is very stateful and hard to preview/mock. Move that state upper in the composable tree

**Comment by oas004** [comment]
Hi, really cool project! I really want to contribute to this. Can I try to do this task? :) I noticed that it was assigned to you @martinbonnin, but if you have not done it yet, could it be up for grabs? :) 

I could not find in the README anything about accepting contributions from outside. Do you know if the are there any guidelines for that? :)

**Comment by martinbonnin** [comment]
Of course, go for it! I've just assigned you. We don't have a CONTRIBUTING.md yet but that's a good callout, we'll work on setting something up.

**Comment by joreilly** [comment]
👋 @oas004 , nice to see you here!

**Comment by martinbonnin** [comment]
Thanks for the PR, that was quick 👏 ! Will look into it but I wanted to mention there's a CONTRIBUTING pull request opened [there](https://github.com/joreilly/Confetti/pull/383). Let us know if you see anything missing that would have helped you bootstrap the project (even though looks like that went fine :)!

**Comment by oas004** [comment]
Amazing! I will have a look! :)
