### ISSUE TITLE
Fix A11y for speaker list

### ISSUE THREAD

**Issue by yschimke** [joreilly/Confetti#377]
From the a11y tests

![image](https://user-images.githubusercontent.com/231923/226680852-b669d8c2-c577-4a2a-a149-4c27caaefb8f.png)

**Comment by yschimke** [comment]
Consider making this clickable item larger.

This item's height is 40dp. Consider making the height of this touch target 48dp or larger.[ Learn more](https://support.google.com/accessibility/android/answer/7101858)

**Comment by joreilly** [comment]
This is re. clicking on speaker to see their details?

**Comment by yschimke** [comment]
Yep, if they are not clickable, it's a bug in the a11y tests I'll raise.
