### ISSUE TITLE
Favourite talks for each conference?

### ISSUE THREAD

**Issue by dbaroncelli** [joreilly/Confetti#378]
I downloaded the app and it seems really useful for browsing the KotlinConf talks.
However it would be even more useful if it was possibile to set favourites talks, adding an extra menu "favourites" item in the bottom bar, which would be populated by the talks who hava a favourite icon clicked.

**Comment by dbaroncelli** [comment]
I just realized the favourites/bookmarks are available for signed in users.
maybe it should be made it more clear, as if you don't login, you wouldn't know

**Comment by joreilly** [comment]
@martinbonnin I think is hoping to also support some kind of anonymous login approach at some point...

**Comment by joreilly** [comment]
Right now we only show bookmark icons when user is logged in but probably good to show those at least from start so user knows that's possible
