### ISSUE TITLE
Status Bar should be light in Dark Mode

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#389]
How to reproduce:

1. Open the app;
2. Select Kotlin Conf;
3. Click in your avatar (top right);
4. Select Settings;
5. In "Dark mode preferences", select Dark Mode;
6. Click OK.

Notice the app has turned into Dark Mode, but the Status Bar is still black.

![Screenshot_20230322-090010](https://user-images.githubusercontent.com/4348197/226853092-497a910a-066a-4f1b-8519-77c5d0531f3b.png)

**Comment by joreilly** [comment]
Ah, well spotted!  Need to see how NowInAndroid for example is handling this.
