### ISSUE TITLE
Remove the AccountViewModel and move that state to the upmost "Route" level

### ISSUE THREAD

**Issue by oas004** [joreilly/Confetti#391]
Making this issue since we discussed it in the thread here (https://github.com/joreilly/Confetti/pull/385#discussion_r1144735106) :) 
I could not find it in the issues. Hope that is okay :)

**Comment by oas004** [comment]
I was wondering a bit about this task. If we remove the AccountViewModel, should then the `SessionsViewModel` expose more than one uiState? Or should it be part of the successState that of the sessions? If that is the case should the accountIcon not be shown if there is an error loading the sessions? :)

Is there something here that I'm missing or any other way that is prefered? @martinbonnin

**Comment by yschimke** [comment]
Yeah, I think a rule that screens have a 1:1 viewmodel makes sense. And like nowinandroid, if uiState updates separately and is used for different parts then it makes sense as 2 flows

**Comment by oas004** [comment]
Okay that makes sense, I'll do that approach then😊

**Comment by martinbonnin** [comment]
Agree with 1 viewmodel per screen. No strong preference whether we want 2 different states or just 1. I guess if the state maps to nested composables, it's easier to make 2, either works for me. 

If we go with 2 different states, I would rename `uiState` to have `sessionsState` & `accountState` (or something like this).

**Comment by oas004** [comment]
I ran into another issue with trying out this. When migrating the functionallity from AccountViewModel to SessionViewModel, the AccountViewModel is injecting Authentication class and WearSettingSync class. These are in the `:androidApp` module but the SessionViewModel is in the shared mobile module. This means I have to move them into that module to avoid a circular dependency issue for the ViewModel if I'm not mistaken. These classes are using some dependencies that I don't think I can implement in the common module.

Was there a reason that the AccountViewModel was not shared between Android and iOS? Is the login part handled differently on iOS? :)

**Comment by oas004** [comment]
I guess I can extend SessionsViewModel and add the Android behavior to that, is that okay? What do you think about that? :)

**Comment by yschimke** [comment]
@oas004 I'd extend as you suggest.

But honestly you are in uncharted territory, so this will be a learning experience for what works well.

**Comment by oas004** [comment]
I got something working, but I'm not 100% sure about the approach. Made a draft in #446

**Comment by oas004** [comment]
Can I close this issue as completed? Or was there anything left regarding this? :) I opened an issue regarding Robolectric for Android if we are going to add integration tests for this :) #522

**Comment by martinbonnin** [comment]
All good, thanks for diving into this!
