### ISSUE TITLE
Android Theme with Dark Mode is unreadable

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#394]
How to reproduce:
1. Open the app;
2. Click on your avatar;
3. Select Settings;
4. Select Android under Theme;
5. Select Dark under Dark Mode Preference.
6. Go back to home, see the sessions are not readable;

Note the Default theme works as expected.

![Screenshot_20230322-213400](https://user-images.githubusercontent.com/4348197/227044077-3fd616f3-78ed-42c1-91e7-7e1bec5bf172.png)

**Comment by joreilly** [comment]
We should compare with nowinandroid app and see what we're missing.

**Comment by joreilly** [comment]
Should be fixed now

![Screenshot_20230326_172206](https://user-images.githubusercontent.com/6302/227790016-d43cf598-a2a3-4e2e-9e2b-e77500cfead5.png)
![Screenshot_20230326_172229](https://user-images.githubusercontent.com/6302/227790018-997ff1c8-bff0-4bc9-b8ce-5e3bad4bebf3.png)
