### ISSUE TITLE
Add bookmark button to session details screen

### ISSUE THREAD

**Issue by joreilly** [joreilly/Confetti#405]

**Comment by marcellogalhardo** [comment]
@joreilly we should include the button in the speaker session list too. 😄

**Comment by marcellogalhardo** [comment]
Ah, we may also want to include the room and the speakers (as a talk can have multiple speakers, it may be useful to see everyone that is involved). Basically, same content from the sessions list item.

**Comment by brunohensel** [comment]
> @joreilly we should include the button in the speaker details sessions list too. 😄

Any suggestions on where to put the bookmark icon on the speaker details screen?

**Comment by joreilly** [comment]
Hmm, I think it was added there already?

**Comment by brunohensel** [comment]
> Hmm, I think it was added there already?

Just pulled the main, and I can't see it. I added it only for the session detail screen.

**Comment by joreilly** [comment]
ah, sorry, I missed the word "speaker" (my brain on go slow here :) ).  I'm not sure if there's as much need to put on speaker details screen....you can always click through to the session and do it there.  We're a bit more limited on speaker screen with space....particularly given speaker can have multiple sessions.  wdyt?

**Comment by brunohensel** [comment]
Yeah, I think you are correct. Looking at the screen, at least on mobile, there is no that much space to add the bookmark in front of each speaker's talk.

**Comment by joreilly** [comment]
will close this issue anyway and we can open another one if needed later
