### ISSUE TITLE
In the search screen, the last results are hidden by the virtual keyboard

### ISSUE THREAD

**Issue by martinbonnin** [joreilly/Confetti#463]
In the screenshot below, there are speakers but can't see them unless I remove the virtual keyboard.

<img src="https://user-images.githubusercontent.com/3974977/228375563-32c7ae0d-f283-4a12-a0bb-f1307564de43.png" width=250/>

**Comment by martinbonnin** [comment]
Also side note/nitpick: what about the "event" icon to represent sessions instead of mic? 

See https://fonts.google.com/icons?selected=Material+Symbols+Outlined:event:FILL@0;wght@400;GRAD@0;opsz@48&icon.query=calendar

**Comment by marcellogalhardo** [comment]
The icon sounds good to me. Keyboard should be easy to fix. 👍

Can you add "good first issue" tag?

**Comment by martinbonnin** [comment]
> Can you add "good first issue" tag?

Good idea, done.

**Comment by marcellogalhardo** [comment]
I can't close it, but it has been fixed on my last PR. cc: @martinbonnin @joreilly
