### ISSUE TITLE
Add navigation from Session Details to Speaker

### ISSUE THREAD

**Issue by marcellogalhardo** [joreilly/Confetti#492]
Clicking on the speaker photo on a session detail should navigate the user to the speaker details screen.

**Comment by oas004** [comment]
This should be added for Android now with #511 :) Not quite sure on how to do it for iOS

**Comment by marcellogalhardo** [comment]
Can we close the issue @joreilly ?

**Comment by joreilly** [comment]
I was going to wait until this was done for iOS client as well.
