### ISSUE TITLE
Consider handling bottom nav (and NavRail) navigation as top-level destinations launched as singleTop who have their own backstack

### ISSUE THREAD

**Issue by StylianosGakis** [joreilly/Confetti#551]
The bottom nav might feel a bit more intuitive to use when adding new destinations on top doesn't make the backstack list grow indefinitely as more destinations are pressed.

Current implementation looks like this:

| Confetti | NiA |
| --- | --- |
| https://user-images.githubusercontent.com/44558292/230629586-f7730731-f389-4a74-a3e2-7e154149952e.mp4 | https://user-images.githubusercontent.com/44558292/230629364-a5254591-e3e5-4298-99d1-5da48128d5b0.mp4 |

We can try to make Confetti function the same way as NiA does with this.

**Comment by joreilly** [comment]
Sound like we might be able to close this following the Decompose updates?

**Comment by StylianosGakis** [comment]
Yeap, just like the other one that I closed, missed this one 😊
