### ISSUE TITLE
DevFest Nantes - Missing data

### ISSUE THREAD

**Issue by RobinCaroff** [joreilly/Confetti#73]
Some models are missing attributs for the DevFest Nantes event.

Here are the ones I noticed :

  * Session :
    * `talkType` (Conference, Quickie, Codelab)
    * `language`
    * `complexity`
    * `openfeedbackId`
  * Speaker :
    * `companyLogo`
    * `city` (e.g.: "Massy, France")
    
[DevFest Nantes' Data source](https://github.com/GDG-Nantes/Devfest2022/tree/master/data)

**Comment by RobinCaroff** [comment]
ping @martinbonnin

**Comment by martinbonnin** [comment]
Current status:

* [ ] Session.talkType
* [x] Session.language
* [x] Session.complexity
* [x] Session.feedbackId
* [x] Speaker.city
* [x] Speaker.companyLogoUrl
