### ISSUE TITLE
DevFest Nantes - Some partners logoUrl return a 404

### ISSUE THREAD

**Issue by RobinCaroff** [joreilly/Confetti#78]
Some DevFest Nantes partners `logoUrl` return a 404;  e.g.: OVH and ISILOG.

This is due to the fact that OVH's logo is a `.webp` and isilog is a `.jpg` image. Is there anything we can do about it ?

An easy fix is to request DevFest Nantes to only use `.png` but it would be great to have a more resilient system.

**Comment by RobinCaroff** [comment]
Ping @martinbonnin

**Comment by martinbonnin** [comment]
Done in https://github.com/joreilly/Confetti/pull/90
