### ISSUE TITLE
Touch up SessionDetails UI

### ISSUE THREAD

**Issue by sophicapri** [joreilly/Confetti#895]
👋🏽 Hello !

I'd like to make the `Speakers` header match the width of the screen and also add some spacing above it when there are no tags. 

Can I ?

<img src="https://github.com/joreilly/Confetti/assets/56972994/95a367a0-97cb-4936-882f-e953e0147c0d" align="left" 
width="300">

<img src="https://github.com/joreilly/Confetti/assets/56972994/f0ca5406-2c1f-4245-982b-4b08bd897d22" align="left" width="300">

**Comment by joreilly** [comment]
Hi @sophicapri , yes, definitely.... contributions very welcome!
