### ISSUE TITLE
Watchos compose 

### ISSUE THREAD

**Issue by ismai117** [joreilly/Confetti#978]
Hi, I just wanted to ask if we can share our kmp UI Components with watchos/apple watches?

I've managed to share the code for Wearos but not watchos.

**Comment by yschimke** [comment]
Wear OS has it's own set of components. I don't think these are designed to work on the Apple Watch.  So I don't think it's intended to build a single UI that works between Wear OS and Apple Watch.

**Comment by yschimke** [comment]
Not clear what to do further on this. Closing.
